name: mdvault

services:
  mdvault:
    image: ghcr.io/victor3spoir/mdvault:dev
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: "600MiB"
        limits:
          cpus: "0.7"
          memory: "800MiB"
    ports:
      - "127.0.0.1:33000:3000"
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_REPO: ${GITHUB_REPO} # Example: 'my-content' NOT 'github.com/user/my-content'

