/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CmsRouteRouteImport } from './routes/cms/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as CmsVaultIndexRouteImport } from './routes/cms/vault/index'
import { Route as CmsSettingsIndexRouteImport } from './routes/cms/settings/index'
import { Route as CmsPostsIndexRouteImport } from './routes/cms/posts/index'
import { Route as CmsMediaIndexRouteImport } from './routes/cms/media/index'
import { Route as CmsArticlesIndexRouteImport } from './routes/cms/articles/index'
import { Route as CmsVaultNewIndexRouteImport } from './routes/cms/vault/new/index'
import { Route as CmsVaultIdIndexRouteImport } from './routes/cms/vault/$id/index'
import { Route as CmsPostsNewIndexRouteImport } from './routes/cms/posts/new/index'
import { Route as CmsPostsSlugIndexRouteImport } from './routes/cms/posts/$slug/index'
import { Route as CmsArticlesNewIndexRouteImport } from './routes/cms/articles/new/index'
import { Route as CmsArticlesIdIndexRouteImport } from './routes/cms/articles/$id/index'
import { Route as CmsArticlesIdEditRouteImport } from './routes/cms/articles/$id/edit'
import { Route as CmsVaultIdEditIndexRouteImport } from './routes/cms/vault/$id/edit/index'
import { Route as CmsPostsSlugEditIndexRouteImport } from './routes/cms/posts/$slug/edit/index'

const CmsRouteRoute = CmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsVaultIndexRoute = CmsVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsSettingsIndexRoute = CmsSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsIndexRoute = CmsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsMediaIndexRoute = CmsMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesIndexRoute = CmsArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsVaultNewIndexRoute = CmsVaultNewIndexRouteImport.update({
  id: '/vault/new/',
  path: '/vault/new/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsVaultIdIndexRoute = CmsVaultIdIndexRouteImport.update({
  id: '/vault/$id/',
  path: '/vault/$id/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsNewIndexRoute = CmsPostsNewIndexRouteImport.update({
  id: '/posts/new/',
  path: '/posts/new/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsSlugIndexRoute = CmsPostsSlugIndexRouteImport.update({
  id: '/posts/$slug/',
  path: '/posts/$slug/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesNewIndexRoute = CmsArticlesNewIndexRouteImport.update({
  id: '/articles/new/',
  path: '/articles/new/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesIdIndexRoute = CmsArticlesIdIndexRouteImport.update({
  id: '/articles/$id/',
  path: '/articles/$id/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesIdEditRoute = CmsArticlesIdEditRouteImport.update({
  id: '/articles/$id/edit',
  path: '/articles/$id/edit',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsVaultIdEditIndexRoute = CmsVaultIdEditIndexRouteImport.update({
  id: '/vault/$id/edit/',
  path: '/vault/$id/edit/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsSlugEditIndexRoute = CmsPostsSlugEditIndexRouteImport.update({
  id: '/posts/$slug/edit/',
  path: '/posts/$slug/edit/',
  getParentRoute: () => CmsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/api/ping': typeof ApiPingRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/articles/': typeof CmsArticlesIndexRoute
  '/cms/media/': typeof CmsMediaIndexRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
  '/cms/settings/': typeof CmsSettingsIndexRoute
  '/cms/vault/': typeof CmsVaultIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/articles/$id/': typeof CmsArticlesIdIndexRoute
  '/cms/articles/new/': typeof CmsArticlesNewIndexRoute
  '/cms/posts/$slug/': typeof CmsPostsSlugIndexRoute
  '/cms/posts/new/': typeof CmsPostsNewIndexRoute
  '/cms/vault/$id/': typeof CmsVaultIdIndexRoute
  '/cms/vault/new/': typeof CmsVaultNewIndexRoute
  '/cms/posts/$slug/edit/': typeof CmsPostsSlugEditIndexRoute
  '/cms/vault/$id/edit/': typeof CmsVaultIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/ping': typeof ApiPingRoute
  '/cms': typeof CmsIndexRoute
  '/cms/articles': typeof CmsArticlesIndexRoute
  '/cms/media': typeof CmsMediaIndexRoute
  '/cms/posts': typeof CmsPostsIndexRoute
  '/cms/settings': typeof CmsSettingsIndexRoute
  '/cms/vault': typeof CmsVaultIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/articles/$id': typeof CmsArticlesIdIndexRoute
  '/cms/articles/new': typeof CmsArticlesNewIndexRoute
  '/cms/posts/$slug': typeof CmsPostsSlugIndexRoute
  '/cms/posts/new': typeof CmsPostsNewIndexRoute
  '/cms/vault/$id': typeof CmsVaultIdIndexRoute
  '/cms/vault/new': typeof CmsVaultNewIndexRoute
  '/cms/posts/$slug/edit': typeof CmsPostsSlugEditIndexRoute
  '/cms/vault/$id/edit': typeof CmsVaultIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/api/ping': typeof ApiPingRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/articles/': typeof CmsArticlesIndexRoute
  '/cms/media/': typeof CmsMediaIndexRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
  '/cms/settings/': typeof CmsSettingsIndexRoute
  '/cms/vault/': typeof CmsVaultIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/articles/$id/': typeof CmsArticlesIdIndexRoute
  '/cms/articles/new/': typeof CmsArticlesNewIndexRoute
  '/cms/posts/$slug/': typeof CmsPostsSlugIndexRoute
  '/cms/posts/new/': typeof CmsPostsNewIndexRoute
  '/cms/vault/$id/': typeof CmsVaultIdIndexRoute
  '/cms/vault/new/': typeof CmsVaultNewIndexRoute
  '/cms/posts/$slug/edit/': typeof CmsPostsSlugEditIndexRoute
  '/cms/vault/$id/edit/': typeof CmsVaultIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/api/media'
    | '/api/ping'
    | '/cms/'
    | '/cms/articles/'
    | '/cms/media/'
    | '/cms/posts/'
    | '/cms/settings/'
    | '/cms/vault/'
    | '/cms/articles/$id/edit'
    | '/cms/articles/$id/'
    | '/cms/articles/new/'
    | '/cms/posts/$slug/'
    | '/cms/posts/new/'
    | '/cms/vault/$id/'
    | '/cms/vault/new/'
    | '/cms/posts/$slug/edit/'
    | '/cms/vault/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/media'
    | '/api/ping'
    | '/cms'
    | '/cms/articles'
    | '/cms/media'
    | '/cms/posts'
    | '/cms/settings'
    | '/cms/vault'
    | '/cms/articles/$id/edit'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/cms/posts/$slug'
    | '/cms/posts/new'
    | '/cms/vault/$id'
    | '/cms/vault/new'
    | '/cms/posts/$slug/edit'
    | '/cms/vault/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cms'
    | '/api/media'
    | '/api/ping'
    | '/cms/'
    | '/cms/articles/'
    | '/cms/media/'
    | '/cms/posts/'
    | '/cms/settings/'
    | '/cms/vault/'
    | '/cms/articles/$id/edit'
    | '/cms/articles/$id/'
    | '/cms/articles/new/'
    | '/cms/posts/$slug/'
    | '/cms/posts/new/'
    | '/cms/vault/$id/'
    | '/cms/vault/new/'
    | '/cms/posts/$slug/edit/'
    | '/cms/vault/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRouteRoute: typeof CmsRouteRouteWithChildren
  ApiMediaRoute: typeof ApiMediaRoute
  ApiPingRoute: typeof ApiPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/vault/': {
      id: '/cms/vault/'
      path: '/vault'
      fullPath: '/cms/vault/'
      preLoaderRoute: typeof CmsVaultIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/settings/': {
      id: '/cms/settings/'
      path: '/settings'
      fullPath: '/cms/settings/'
      preLoaderRoute: typeof CmsSettingsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/': {
      id: '/cms/posts/'
      path: '/posts'
      fullPath: '/cms/posts/'
      preLoaderRoute: typeof CmsPostsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/media/': {
      id: '/cms/media/'
      path: '/media'
      fullPath: '/cms/media/'
      preLoaderRoute: typeof CmsMediaIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/': {
      id: '/cms/articles/'
      path: '/articles'
      fullPath: '/cms/articles/'
      preLoaderRoute: typeof CmsArticlesIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/vault/new/': {
      id: '/cms/vault/new/'
      path: '/vault/new'
      fullPath: '/cms/vault/new/'
      preLoaderRoute: typeof CmsVaultNewIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/vault/$id/': {
      id: '/cms/vault/$id/'
      path: '/vault/$id'
      fullPath: '/cms/vault/$id/'
      preLoaderRoute: typeof CmsVaultIdIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/new/': {
      id: '/cms/posts/new/'
      path: '/posts/new'
      fullPath: '/cms/posts/new/'
      preLoaderRoute: typeof CmsPostsNewIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/$slug/': {
      id: '/cms/posts/$slug/'
      path: '/posts/$slug'
      fullPath: '/cms/posts/$slug/'
      preLoaderRoute: typeof CmsPostsSlugIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/new/': {
      id: '/cms/articles/new/'
      path: '/articles/new'
      fullPath: '/cms/articles/new/'
      preLoaderRoute: typeof CmsArticlesNewIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/$id/': {
      id: '/cms/articles/$id/'
      path: '/articles/$id'
      fullPath: '/cms/articles/$id/'
      preLoaderRoute: typeof CmsArticlesIdIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/$id/edit': {
      id: '/cms/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/cms/articles/$id/edit'
      preLoaderRoute: typeof CmsArticlesIdEditRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/vault/$id/edit/': {
      id: '/cms/vault/$id/edit/'
      path: '/vault/$id/edit'
      fullPath: '/cms/vault/$id/edit/'
      preLoaderRoute: typeof CmsVaultIdEditIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/$slug/edit/': {
      id: '/cms/posts/$slug/edit/'
      path: '/posts/$slug/edit'
      fullPath: '/cms/posts/$slug/edit/'
      preLoaderRoute: typeof CmsPostsSlugEditIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
  }
}

interface CmsRouteRouteChildren {
  CmsIndexRoute: typeof CmsIndexRoute
  CmsArticlesIndexRoute: typeof CmsArticlesIndexRoute
  CmsMediaIndexRoute: typeof CmsMediaIndexRoute
  CmsPostsIndexRoute: typeof CmsPostsIndexRoute
  CmsSettingsIndexRoute: typeof CmsSettingsIndexRoute
  CmsVaultIndexRoute: typeof CmsVaultIndexRoute
  CmsArticlesIdEditRoute: typeof CmsArticlesIdEditRoute
  CmsArticlesIdIndexRoute: typeof CmsArticlesIdIndexRoute
  CmsArticlesNewIndexRoute: typeof CmsArticlesNewIndexRoute
  CmsPostsSlugIndexRoute: typeof CmsPostsSlugIndexRoute
  CmsPostsNewIndexRoute: typeof CmsPostsNewIndexRoute
  CmsVaultIdIndexRoute: typeof CmsVaultIdIndexRoute
  CmsVaultNewIndexRoute: typeof CmsVaultNewIndexRoute
  CmsPostsSlugEditIndexRoute: typeof CmsPostsSlugEditIndexRoute
  CmsVaultIdEditIndexRoute: typeof CmsVaultIdEditIndexRoute
}

const CmsRouteRouteChildren: CmsRouteRouteChildren = {
  CmsIndexRoute: CmsIndexRoute,
  CmsArticlesIndexRoute: CmsArticlesIndexRoute,
  CmsMediaIndexRoute: CmsMediaIndexRoute,
  CmsPostsIndexRoute: CmsPostsIndexRoute,
  CmsSettingsIndexRoute: CmsSettingsIndexRoute,
  CmsVaultIndexRoute: CmsVaultIndexRoute,
  CmsArticlesIdEditRoute: CmsArticlesIdEditRoute,
  CmsArticlesIdIndexRoute: CmsArticlesIdIndexRoute,
  CmsArticlesNewIndexRoute: CmsArticlesNewIndexRoute,
  CmsPostsSlugIndexRoute: CmsPostsSlugIndexRoute,
  CmsPostsNewIndexRoute: CmsPostsNewIndexRoute,
  CmsVaultIdIndexRoute: CmsVaultIdIndexRoute,
  CmsVaultNewIndexRoute: CmsVaultNewIndexRoute,
  CmsPostsSlugEditIndexRoute: CmsPostsSlugEditIndexRoute,
  CmsVaultIdEditIndexRoute: CmsVaultIdEditIndexRoute,
}

const CmsRouteRouteWithChildren = CmsRouteRoute._addFileChildren(
  CmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRouteRoute: CmsRouteRouteWithChildren,
  ApiMediaRoute: ApiMediaRoute,
  ApiPingRoute: ApiPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
