/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CmsRouteRouteImport } from './routes/cms/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as CmsSettingsRouteImport } from './routes/cms/settings'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as CmsPostsIndexRouteImport } from './routes/cms/posts/index'
import { Route as CmsMediaIndexRouteImport } from './routes/cms/media/index'
import { Route as CmsArticlesIndexRouteImport } from './routes/cms/articles/index'
import { Route as CmsPostsNewRouteImport } from './routes/cms/posts/new'
import { Route as CmsPostsSlugRouteImport } from './routes/cms/posts/$slug'
import { Route as CmsArticlesNewRouteImport } from './routes/cms/articles/new'
import { Route as CmsArticlesIdRouteImport } from './routes/cms/articles/$id'
import { Route as CmsPostsSlugEditRouteImport } from './routes/cms/posts/$slug/edit'
import { Route as CmsArticlesIdEditRouteImport } from './routes/cms/articles/$id/edit'

const CmsRouteRoute = CmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsSettingsRoute = CmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CmsRouteRoute,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsPostsIndexRoute = CmsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsMediaIndexRoute = CmsMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesIndexRoute = CmsArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsNewRoute = CmsPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsSlugRoute = CmsPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesNewRoute = CmsArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsArticlesIdRoute = CmsArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsSlugEditRoute = CmsPostsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CmsPostsSlugRoute,
} as any)
const CmsArticlesIdEditRoute = CmsArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CmsArticlesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/api/image': typeof ApiImageRoute
  '/cms/settings': typeof CmsSettingsRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/articles/$id': typeof CmsArticlesIdRouteWithChildren
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/cms/posts/$slug': typeof CmsPostsSlugRouteWithChildren
  '/cms/posts/new': typeof CmsPostsNewRoute
  '/cms/articles/': typeof CmsArticlesIndexRoute
  '/cms/media/': typeof CmsMediaIndexRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/posts/$slug/edit': typeof CmsPostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/image': typeof ApiImageRoute
  '/cms/settings': typeof CmsSettingsRoute
  '/cms': typeof CmsIndexRoute
  '/cms/articles/$id': typeof CmsArticlesIdRouteWithChildren
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/cms/posts/$slug': typeof CmsPostsSlugRouteWithChildren
  '/cms/posts/new': typeof CmsPostsNewRoute
  '/cms/articles': typeof CmsArticlesIndexRoute
  '/cms/media': typeof CmsMediaIndexRoute
  '/cms/posts': typeof CmsPostsIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/posts/$slug/edit': typeof CmsPostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/api/image': typeof ApiImageRoute
  '/cms/settings': typeof CmsSettingsRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/articles/$id': typeof CmsArticlesIdRouteWithChildren
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/cms/posts/$slug': typeof CmsPostsSlugRouteWithChildren
  '/cms/posts/new': typeof CmsPostsNewRoute
  '/cms/articles/': typeof CmsArticlesIndexRoute
  '/cms/media/': typeof CmsMediaIndexRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
  '/cms/articles/$id/edit': typeof CmsArticlesIdEditRoute
  '/cms/posts/$slug/edit': typeof CmsPostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/api/image'
    | '/cms/settings'
    | '/cms/'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/cms/posts/$slug'
    | '/cms/posts/new'
    | '/cms/articles/'
    | '/cms/media/'
    | '/cms/posts/'
    | '/cms/articles/$id/edit'
    | '/cms/posts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/image'
    | '/cms/settings'
    | '/cms'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/cms/posts/$slug'
    | '/cms/posts/new'
    | '/cms/articles'
    | '/cms/media'
    | '/cms/posts'
    | '/cms/articles/$id/edit'
    | '/cms/posts/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/cms'
    | '/api/image'
    | '/cms/settings'
    | '/cms/'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/cms/posts/$slug'
    | '/cms/posts/new'
    | '/cms/articles/'
    | '/cms/media/'
    | '/cms/posts/'
    | '/cms/articles/$id/edit'
    | '/cms/posts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRouteRoute: typeof CmsRouteRouteWithChildren
  ApiImageRoute: typeof ApiImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/settings': {
      id: '/cms/settings'
      path: '/settings'
      fullPath: '/cms/settings'
      preLoaderRoute: typeof CmsSettingsRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/posts/': {
      id: '/cms/posts/'
      path: '/posts'
      fullPath: '/cms/posts/'
      preLoaderRoute: typeof CmsPostsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/media/': {
      id: '/cms/media/'
      path: '/media'
      fullPath: '/cms/media/'
      preLoaderRoute: typeof CmsMediaIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/': {
      id: '/cms/articles/'
      path: '/articles'
      fullPath: '/cms/articles/'
      preLoaderRoute: typeof CmsArticlesIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/new': {
      id: '/cms/posts/new'
      path: '/posts/new'
      fullPath: '/cms/posts/new'
      preLoaderRoute: typeof CmsPostsNewRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/$slug': {
      id: '/cms/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/cms/posts/$slug'
      preLoaderRoute: typeof CmsPostsSlugRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/new': {
      id: '/cms/articles/new'
      path: '/articles/new'
      fullPath: '/cms/articles/new'
      preLoaderRoute: typeof CmsArticlesNewRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/articles/$id': {
      id: '/cms/articles/$id'
      path: '/articles/$id'
      fullPath: '/cms/articles/$id'
      preLoaderRoute: typeof CmsArticlesIdRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/$slug/edit': {
      id: '/cms/posts/$slug/edit'
      path: '/edit'
      fullPath: '/cms/posts/$slug/edit'
      preLoaderRoute: typeof CmsPostsSlugEditRouteImport
      parentRoute: typeof CmsPostsSlugRoute
    }
    '/cms/articles/$id/edit': {
      id: '/cms/articles/$id/edit'
      path: '/edit'
      fullPath: '/cms/articles/$id/edit'
      preLoaderRoute: typeof CmsArticlesIdEditRouteImport
      parentRoute: typeof CmsArticlesIdRoute
    }
  }
}

interface CmsArticlesIdRouteChildren {
  CmsArticlesIdEditRoute: typeof CmsArticlesIdEditRoute
}

const CmsArticlesIdRouteChildren: CmsArticlesIdRouteChildren = {
  CmsArticlesIdEditRoute: CmsArticlesIdEditRoute,
}

const CmsArticlesIdRouteWithChildren = CmsArticlesIdRoute._addFileChildren(
  CmsArticlesIdRouteChildren,
)

interface CmsPostsSlugRouteChildren {
  CmsPostsSlugEditRoute: typeof CmsPostsSlugEditRoute
}

const CmsPostsSlugRouteChildren: CmsPostsSlugRouteChildren = {
  CmsPostsSlugEditRoute: CmsPostsSlugEditRoute,
}

const CmsPostsSlugRouteWithChildren = CmsPostsSlugRoute._addFileChildren(
  CmsPostsSlugRouteChildren,
)

interface CmsRouteRouteChildren {
  CmsSettingsRoute: typeof CmsSettingsRoute
  CmsIndexRoute: typeof CmsIndexRoute
  CmsArticlesIdRoute: typeof CmsArticlesIdRouteWithChildren
  CmsArticlesNewRoute: typeof CmsArticlesNewRoute
  CmsPostsSlugRoute: typeof CmsPostsSlugRouteWithChildren
  CmsPostsNewRoute: typeof CmsPostsNewRoute
  CmsArticlesIndexRoute: typeof CmsArticlesIndexRoute
  CmsMediaIndexRoute: typeof CmsMediaIndexRoute
  CmsPostsIndexRoute: typeof CmsPostsIndexRoute
}

const CmsRouteRouteChildren: CmsRouteRouteChildren = {
  CmsSettingsRoute: CmsSettingsRoute,
  CmsIndexRoute: CmsIndexRoute,
  CmsArticlesIdRoute: CmsArticlesIdRouteWithChildren,
  CmsArticlesNewRoute: CmsArticlesNewRoute,
  CmsPostsSlugRoute: CmsPostsSlugRouteWithChildren,
  CmsPostsNewRoute: CmsPostsNewRoute,
  CmsArticlesIndexRoute: CmsArticlesIndexRoute,
  CmsMediaIndexRoute: CmsMediaIndexRoute,
  CmsPostsIndexRoute: CmsPostsIndexRoute,
}

const CmsRouteRouteWithChildren = CmsRouteRoute._addFileChildren(
  CmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRouteRoute: CmsRouteRouteWithChildren,
  ApiImageRoute: ApiImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
